apiVersion: v1
kind: List
items:
  {{- range $iname, $instance := .Values.instances }}
  {{- range $dname, $deployment := $instance.deployments }}
  {{- $deploymentContext := dict "iname" $iname "instance" $instance "name" $dname "deployment" $deployment "root" $ }}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ $dname }}
      annotations:
        labels:
          {{- include "platformex.kubernetesAppLabels" $deploymentContext | indent 10 }}
          {{- include "platformex.globalLabels" $ | indent 10 }}
    spec:
      revisionHistoryLimit: 3
      {{- include "platformex.deployment.replicas" $deploymentContext | indent 6 }}
      selector:
        matchLabels:
          {{- include "platformex.kubernetesAppLabels" $deploymentContext | indent 10 }}
      template:
        metadata:
          labels:
            {{- include "platformex.kubernetesAppLabels" $deploymentContext | indent 12 }}
            {{- include "platformex.globalLabels" $ | indent 12 }}
        spec:
          {{- include "platformex.deployment.volumes" $deploymentContext | indent 10 }}
          {{- include "platformex.deployment.nodeSelector" $deploymentContext | indent 10 }}
          {{- include "platformex.deployment.imagePullSecrets" $deploymentContext | indent 10 }}
          {{- if $deployment.initContainers }}
          initContainers:
            {{- range $icName, $initContainer := $deployment.initContainers }}
            {{- $icContext := dict "iname" $iname "instance" $instance "name" $icName "container" $initContainer "root" $ }}
            - {{- include "platformex.containerFull" $icContext | indent 14 }}
            {{- end }}
          {{- end }}
          containers:
            {{- range $cName, $container := $deployment.containers }}
            {{- $containerContext := dict "iname" $iname "instance" $instance "name" $cName "container" $container "root" $ }}
            - {{- include "platformex.containerFull" $containerContext | indent 14 }}
            {{- end }}
  {{- end }}
  {{- end }}