apiVersion: v1
kind: List
items:
  {{- range $iname, $instance := .Values.instances }}
  {{- range $dname, $deployment := $instance.deployments }}
  {{- $deploymentContext := dict "iname" $iname "instance" $instance "name" $dname "deployment" $deployment "root" $ }}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ $dname }}
      annotations:
        labels:
          {{- include "platformex.kubernetesAppLabels" $deploymentContext | indent 10 }}
          {{- include "platformex.globalLabels" $ | indent 10 }}
    spec:
      revisionHistoryLimit: 3
      {{- include "platformex.deployment.replicas" $deploymentContext | indent 6 }}
      selector:
        matchLabels:
          {{- include "platformex.kubernetesAppLabels" $deploymentContext | indent 10 }}
      template:
        metadata:
          labels:
            {{- include "platformex.kubernetesAppLabels" $deploymentContext | indent 12 }}
            {{- include "platformex.globalLabels" $ | indent 12 }}
        spec:
          {{- include "platformex.deployment.volumes" $deploymentContext | indent 10 }}
          {{- include "platformex.deployment.nodeSelector" $deploymentContext | indent 10 }}
          {{- include "platformex.deployment.imagePullSecrets" $deploymentContext | indent 10 }}
          {{- if $deployment.initContainers }}
          initContainers:
            {{- range $icName, $initContainer := $deployment.initContainers }}
            {{- $icContext := dict "iname" $iname "instance" $instance "name" $icName "container" $initContainer "root" $ }}
            - name: {{ $icName }}
              {{- include "platformex.deployment.volumeMounts" $initContainer | indent 14 }}
              {{- include "platformex.deployment.envFrom" $icContext | indent 14 }}
              {{- include "platformex.deployment.env" $icContext | indent 14 }}
{{- /*              {{- include "platformex.deployment.imagePullPolicy" $icContext | indent 14 }}*/}}
              {{- include "platformex.deployment.image" $icContext | indent 14 }}
{{- /*              {{- include "platformex.deployment.command" $initContainer | indent 14 }}*/}}
{{- /*              {{- include "platformex.deployment.lifecycle" $initContainer | indent 14 }}*/}}
{{- /*              {{- include "platformex.deployment.ports" $initContainer | indent 14 }}*/}}
{{- /*              {{- include "platformex.deployment.liveness" $initContainer | indent 14 }}*/}}
{{- /*              {{- include "platformex.deployment.readiness" $initContainer | indent 14 }}*/}}
{{- /*              {{- include "platformex.deployment.startup" $initContainer | indent 14 }}*/}}
{{- /*              {{- include "platformex.deployment.resources" $initContainer | indent 14 }}*/}}
            {{- end }}
          {{- end }}
          containers:
            {{- range $cName, $container := $deployment.containers }}
            {{- $containerContext := dict "iname" $iname "instance" $instance "name" $cName "container" $container "root" $ }}
            - name: {{ $cName }}
              {{- include "platformex.deployment.envFrom" $containerContext | indent 14 }}
              {{- include "platformex.deployment.env" $containerContext | indent 14 }}
              {{- include "platformex.deployment.image" $containerContext | indent 14 }}
            {{- end }}
  {{- end }}
  {{- end }}