apiVersion: v1
kind: List
items:
  {{- range .Values.traefikMiddlewares }}
  - apiVersion: traefik.containo.us/v1alpha1
    kind: Middleware
    metadata:
      name: {{ .name }}
      labels:
        {{- include "platformex.globalLabels" $ | indent 8 }}
    spec:
      {{- toYaml .spec | nindent 6 }}
  {{- end }}