apiVersion: v1
kind: List
items:
  {{- range $name, $secret := .Values.sealedSecrets }}
  {{- if $.Capabilities.APIVersions.Has "bitnami.com/v1alpha1/SealedSecret" }}
  {{- else }}
  {{- fail "You need to install sealed-secrets operator and CRDs in order to use sealedSecrets." }}
  {{- end }}
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "platformex.globalLabels" $ | indent 10 }}
      name: "{{ required "name is required!" $secret.name }}"
      {{- if $secret.namespace }}
      namespace: {{ $secret.namespace | quote }}
      {{- end }}
    spec:
      encryptedData:
        {{- range $secret.sealedData }}
        {{ .key }}: {{ .value | quote }}
        {{- end }}
      template:
        metadata:
          name: "{{ $secret.name }}"
        {{- if $secret.data }}
        data:
          {{- range $secret.data }}
          {{ .key }}: {{ .value | quote }}
          {{- end }}
        {{- end }}
  {{- end }}