apiVersion: v2
name: platformex
description: Flexible helm chart to deploy your apps to kubernetes cluster.

type: application

# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

appVersion: 1.0.0

